# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gps_navigation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gps_navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gps_navigation.proto\x12\x0egps_navigation\x1a\x1bgoogle/protobuf/empty.proto\",\n\tDescartes\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"1\n\x05\x45uler\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"\\\n\x04Pose\x12+\n\x08position\x18\x01 \x01(\x0b\x32\x19.gps_navigation.Descartes\x12\'\n\x08\x61ttitude\x18\x02 \x01(\x0b\x32\x15.gps_navigation.Euler\"\x8a\x01\n\x05State\x12+\n\x08position\x18\x01 \x01(\x0b\x32\x19.gps_navigation.Descartes\x12+\n\x08velocity\x18\x02 \x01(\x0b\x32\x19.gps_navigation.Descartes\x12\'\n\x08\x61ttitude\x18\x03 \x01(\x0b\x32\x15.gps_navigation.Euler\"*\n\x08Response\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"e\n\x0cNaviResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07\x61rrived\x18\x03 \x01(\x08\x12$\n\x05state\x18\x04 \x01(\x0b\x32\x15.gps_navigation.State2\x93\x02\n\x11GPSNaviController\x12@\n\x0esetDestination\x12\x14.gps_navigation.Pose\x1a\x18.gps_navigation.Response\x12\x43\n\tstartNavi\x12\x16.google.protobuf.Empty\x1a\x1c.gps_navigation.NaviResponse0\x01\x12<\n\x08stopNavi\x12\x16.google.protobuf.Empty\x1a\x18.gps_navigation.Response\x12\x39\n\x08getState\x12\x16.google.protobuf.Empty\x1a\x15.gps_navigation.Stateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gps_navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCARTES']._serialized_start=69
  _globals['_DESCARTES']._serialized_end=113
  _globals['_EULER']._serialized_start=115
  _globals['_EULER']._serialized_end=164
  _globals['_POSE']._serialized_start=166
  _globals['_POSE']._serialized_end=258
  _globals['_STATE']._serialized_start=261
  _globals['_STATE']._serialized_end=399
  _globals['_RESPONSE']._serialized_start=401
  _globals['_RESPONSE']._serialized_end=443
  _globals['_NAVIRESPONSE']._serialized_start=445
  _globals['_NAVIRESPONSE']._serialized_end=546
  _globals['_GPSNAVICONTROLLER']._serialized_start=549
  _globals['_GPSNAVICONTROLLER']._serialized_end=824
# @@protoc_insertion_point(module_scope)
