# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import gps_navigation_pb2 as gps__navigation__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gps_navigation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPSNaviControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setDestination = channel.unary_unary(
                '/gps_navigation.GPSNaviController/setDestination',
                request_serializer=gps__navigation__pb2.Pose.SerializeToString,
                response_deserializer=gps__navigation__pb2.Response.FromString,
                _registered_method=True)
        self.startNavi = channel.unary_stream(
                '/gps_navigation.GPSNaviController/startNavi',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gps__navigation__pb2.NaviResponse.FromString,
                _registered_method=True)
        self.stopNavi = channel.unary_unary(
                '/gps_navigation.GPSNaviController/stopNavi',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gps__navigation__pb2.Response.FromString,
                _registered_method=True)
        self.getState = channel.unary_unary(
                '/gps_navigation.GPSNaviController/getState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gps__navigation__pb2.State.FromString,
                _registered_method=True)


class GPSNaviControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setDestination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startNavi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopNavi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPSNaviControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.setDestination,
                    request_deserializer=gps__navigation__pb2.Pose.FromString,
                    response_serializer=gps__navigation__pb2.Response.SerializeToString,
            ),
            'startNavi': grpc.unary_stream_rpc_method_handler(
                    servicer.startNavi,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gps__navigation__pb2.NaviResponse.SerializeToString,
            ),
            'stopNavi': grpc.unary_unary_rpc_method_handler(
                    servicer.stopNavi,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gps__navigation__pb2.Response.SerializeToString,
            ),
            'getState': grpc.unary_unary_rpc_method_handler(
                    servicer.getState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gps__navigation__pb2.State.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gps_navigation.GPSNaviController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gps_navigation.GPSNaviController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPSNaviController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gps_navigation.GPSNaviController/setDestination',
            gps__navigation__pb2.Pose.SerializeToString,
            gps__navigation__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def startNavi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gps_navigation.GPSNaviController/startNavi',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gps__navigation__pb2.NaviResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stopNavi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gps_navigation.GPSNaviController/stopNavi',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gps__navigation__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gps_navigation.GPSNaviController/getState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gps__navigation__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
